-- V1 baseline — Flyway 도입(HBB1-330) 시점의 현 스키마(@Entity 10개 기준, docs/erd.md).
--
-- prod와 기존 로컬 볼륨은 Hibernate ddl-auto가 이미 만든 스키마라 baseline-on-migrate로 이 파일을 건너뛰고
-- history에 baseline(1)만 기록한다. 새 DB(테스트·새 로컬 볼륨)만 이 파일로 생성한다. 그래서 타입·제약·인덱스는
-- Hibernate가 만든 것과 동일하게 맞췄고(개선 없음), 이름도 Hibernate/PostgreSQL 자동 부여 이름을 그대로 쓴다
-- (FK 해시 이름, unnamed 제약의 <table>_<column>_check / _key) — 환경 간 이름이 갈리면 이후 DROP·RENAME
-- 마이그레이션이 환경별로 달라진다.
--
-- 범위 밖: 타 레포 소유 테이블(interview_transcript·interview_metrics — Kkori-AI 에이전트, resume_chunks·
-- report_generation_jobs — Worker)과 pgvector 확장은 각 레포가 관리한다(docs/erd.md 테이블 소유).
--
-- 스키마 변경 규칙: 엔티티를 바꾸면 V{n} 파일을 함께 추가한다(적용된 파일은 수정 금지 — 체크섬 검증).
-- enum 값 추가는 컬럼의 CHECK 제약 교체(DROP + ADD)를 동반한다 — ddl-auto validate는 CHECK·인덱스·유니크를 검사하지 않는다.

-- ── user 도메인 ─────────────────────────────────────────────────────────────

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email       VARCHAR(255),
    name        VARCHAR(100),
    provider_id VARCHAR(64) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT ux_users_provider_id UNIQUE (provider_id)
);

CREATE TABLE user_consent (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT NOT NULL,
    consent_type VARCHAR(32) NOT NULL CHECK (consent_type IN ('PRIVACY', 'AUDIO_USAGE', 'RESUME_USAGE', 'MARKETING')),
    action       VARCHAR(16) NOT NULL CHECK (action IN ('AGREED', 'WITHDRAWN')),
    version      INTEGER NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX ix_user_consent_user_id ON user_consent (user_id);

CREATE TABLE deletion_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id      BIGINT NOT NULL,
    provider_id  VARCHAR(64),
    requested_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    purged_at    TIMESTAMP(6) WITH TIME ZONE,
    status       VARCHAR(16) NOT NULL CHECK (status IN ('PENDING_PURGE', 'PURGING', 'PURGED', 'FAILED', 'CANCELLED')),
    purge_detail JSONB,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

-- ── auth 도메인 ─────────────────────────────────────────────────────────────

CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    jti         VARCHAR(36) NOT NULL,
    expired_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at  TIMESTAMP(6) WITH TIME ZONE,
    replaced_by VARCHAR(64),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT ux_refresh_token_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_refresh_token_user_id ON refresh_token (user_id);

-- ── resume 도메인 ───────────────────────────────────────────────────────────

CREATE TABLE resumes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id              BIGINT NOT NULL,
    title                VARCHAR(255) NOT NULL,
    file_hash            VARCHAR(64) NOT NULL,
    original_file_bucket VARCHAR(255) NOT NULL,
    original_file_key    VARCHAR(255) NOT NULL,
    original_file_name   VARCHAR(255) NOT NULL,
    file_size            BIGINT NOT NULL,
    mime_type            VARCHAR(255) NOT NULL,
    page_count           INTEGER NOT NULL,
    structured_data      JSONB,
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at           TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id)
);

-- 활성 이력서의 (user_id, file_hash) 유일성 — 동시 중복 업로드 레이스의 최종 심판(docs/requirements/resume/resume.md §1).
-- 전체 컬럼 유니크로 걸면 soft delete 후 같은 파일 재업로드가 막히므로 WHERE deleted_at IS NULL 부분 인덱스.
-- JPA로 표현할 수 없어 기동 시 JDBC로 만들던 것(구 ResumeSchemaConfig)을 여기로 이관했다.
CREATE UNIQUE INDEX ux_resumes_active_user_file_hash ON resumes (user_id, file_hash) WHERE deleted_at IS NULL;

CREATE TABLE resume_analysis_status (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resume_id      BIGINT NOT NULL,
    parse_status   VARCHAR(255) NOT NULL CHECK (parse_status IN ('UPLOADED', 'PARSING', 'TEXT_EXTRACTING', 'STRUCTURING', 'PARSED', 'EMBEDDING', 'EMBEDDED', 'FAILED')),
    parser_version VARCHAR(255),
    error_message  TEXT,
    retry_count    INTEGER NOT NULL,
    started_at     TIMESTAMP(6) WITH TIME ZONE,
    completed_at   TIMESTAMP(6) WITH TIME ZONE,
    failed_at      TIMESTAMP(6) WITH TIME ZONE,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at     TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    -- Hibernate ddl-auto update가 별도 ALTER로 만든 유니크라 PG 자동 이름(_key)이 아닌 Hibernate 해시 이름이다(prod·로컬 볼륨 실측)
    CONSTRAINT ukbei0tscop126xe5d0qkoj6txl UNIQUE (resume_id),
    -- @OneToOne 연관이 만든 유일한 FK — 도메인 간 참조는 무FK 방침(docs/erd.md 공통 규칙)이라 이 하나뿐이다
    CONSTRAINT fk9lmicp1xh7os8pl1san4wpjrg FOREIGN KEY (resume_id) REFERENCES resumes
);

-- ── session 도메인 ──────────────────────────────────────────────────────────

CREATE TABLE interview_session (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id              BIGINT NOT NULL,
    resume_id            BIGINT,
    interview_type       VARCHAR(16) NOT NULL CHECK (interview_type IN ('THIRTY_MIN', 'FIVE_MIN')),
    position             VARCHAR(16) NOT NULL CHECK (position IN ('BACKEND', 'FRONTEND')),
    status               VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'ACTIVE', 'INTERRUPTED', 'AGENT_LOST', 'ENDED', 'ABORTED')),
    livekit_room         VARCHAR(255) NOT NULL,
    started_at           TIMESTAMP(6) WITH TIME ZONE,
    ended_at             TIMESTAMP(6) WITH TIME ZONE,
    disconnected_at      TIMESTAMP(6) WITH TIME ZONE,
    end_requested_at     TIMESTAMP(6) WITH TIME ZONE,
    agent_lost_at        TIMESTAMP(6) WITH TIME ZONE,
    redispatched_at      TIMESTAMP(6) WITH TIME ZONE,
    egress_id            VARCHAR(255),
    recording_bucket     VARCHAR(255),
    recording_object_key VARCHAR(255),
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at           TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT ux_interview_session_livekit_room UNIQUE (livekit_room)
);

CREATE INDEX ix_interview_session_user_id_status ON interview_session (user_id, status);

-- ── report 도메인 (정의는 Spring, 행 생성·갱신은 Worker — docs/erd.md 테이블 소유) ──

CREATE TABLE reports (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id                   BIGINT NOT NULL,
    interview_session_id      BIGINT NOT NULL,
    resume_id                 BIGINT,
    status                    VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')),
    overall_score             INTEGER,
    delivery_score            INTEGER,
    summary                   TEXT,
    resume_file_name_snapshot VARCHAR(255) NOT NULL,
    weakness_tag_summary      JSONB,
    failed_reason             TEXT,
    text_analyzed_at          TIMESTAMP(6) WITH TIME ZONE,
    audio_analyzed_at         TIMESTAMP(6) WITH TIME ZONE,
    completed_at              TIMESTAMP(6) WITH TIME ZONE,
    created_at                TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at                TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at                TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_reports_interview_session_id UNIQUE (interview_session_id)
);

CREATE TABLE report_scores (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    report_id                BIGINT NOT NULL,
    logic_score              INTEGER NOT NULL,
    specificity_score        INTEGER NOT NULL,
    technical_accuracy_score INTEGER NOT NULL,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at               TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_report_scores_report_id UNIQUE (report_id)
);

CREATE TABLE report_feedbacks (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    report_id                BIGINT NOT NULL,
    question_number          INTEGER NOT NULL,
    logic_score              INTEGER NOT NULL,
    specificity_score        INTEGER NOT NULL,
    technical_accuracy_score INTEGER NOT NULL,
    feedback                 TEXT NOT NULL,
    weakness_tags            JSONB,
    improvement_tasks        JSONB,
    resume_context           JSONB,
    created_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    deleted_at               TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT uk_report_feedbacks_report_id_question_number UNIQUE (report_id, question_number)
);
